name: tarea8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons: 
  android: true
  ios: true
  image_path: 'assets/elecciones_20220905.png'

flutter:
  uses-material-design: true
  assets: 
    - assets/Foto.png
    - assets/elecciones_20220905.png
